<?php
    $goth_id = [
"AgADAgADe8QxG3FNzRCOylZNIOVjwETkgQ0ABH8xKtFrRNRjCggCAAEC",
"AgADAgADfMQxG3FNzRCT_d1aW4rjk3vngQ0ABOnqBKcef9jfswwCAAEC",
"AgADAgADfcQxG3FNzRBs4_p8WhgaNUfigQ0ABLURfCZYc6Y2MBECAAEC",
"AgADAgADfsQxG3FNzRBtSXHQoHQXEBMJSw0ABLdZt5UarYCOf04BAAEC",
"AgADAgADf8QxG3FNzRCiFWVS0Xv8OFUwSw0ABE0Wu00R7S76Rl8BAAEC",
"AgADAgADgMQxG3FNzRBqLgbhELkFwbkvSw0ABLEppLV7Sx9rWWABAAEC",
"AgADAgADgcQxG3FNzRCaBcJF8keFIigSSw0ABLrBXULA2eZ8VUoBAAEC",
"AgADAgADgsQxG3FNzRDLvBbGzBIEwxLZgQ0ABK5ghWP540DqHQ0CAAEC",
"AgADAgADg8QxG3FNzRCf4lfA0EVTELwISw0ABCwvQdmRGqGTFkwBAAEC",
"AgADAgADhMQxG3FNzRBrlihipYQt5gwvSw0ABOCzfkTMOnBDPV4BAAEC",
"AgADAgADhcQxG3FNzRAH4pDmMsA8QBHRgQ0ABDMPliJ7LvGJfw8CAAEC",
"AgADAgADhsQxG3FNzRAiW25Y0oM2P-0ySw0ABECZlwVINsnGy10BAAEC",
"AgADAgADh8QxG3FNzRC0iQOH-cW2U1bWgQ0ABA8pEk-jJdxkww0CAAEC",
"AgADAgADiMQxG3FNzRD706fqDAcu2wsNSw0ABNjI_szW-PbMUlABAAEC",
"AgADAgADicQxG3FNzRD-AAHGiJHhHhku3YENAAQU-G4eQD3i_VsMAgABAg",
"AgADAgADisQxG3FNzRCn-s_udLSBJLnWgQ0ABPZdPk69ssKsuwgCAAEC",
"AgADAgADi8QxG3FNzRBjYMgCgRcYTe0RSw0ABGIe7XCgMw9fr0cBAAEC",
    ];

    
    $rand = array_rand($goth_id);
    $count_goth = count($goth_id);
?>
